import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./utils/StoreProvider";
import ToggleContextProvider from "./utils/ToggleContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Feast Fusion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <ToggleContextProvider>
            {children}
          </ToggleContextProvider>
        </StoreProvider>
        </body>
    </html>
  );
}
